-- Stream-Guard-Kafka Database Initialization Script
-- PostgreSQL 15+ Schema for Fraud Detection System

-- Create extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- Main table: All processed transactions
-- ============================================================================
CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(50) NOT NULL UNIQUE,
    account_id VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    transaction_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    merchant VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT positive_amount CHECK (amount >= 0)
);

-- ============================================================================
-- Fraud alerts table: Alerts generated by ksqlDB + Python
-- ============================================================================
CREATE TABLE IF NOT EXISTS fraud_alerts (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(50) NOT NULL,
    account_id VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    transaction_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    fraud_type VARCHAR(50) NOT NULL,
    fraud_reason TEXT NOT NULL,
    risk_score INT NOT NULL DEFAULT 0,
    source VARCHAR(20) NOT NULL DEFAULT 'ksqldb',  -- 'ksqldb' or 'python'
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT valid_risk_score CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT valid_source CHECK (source IN ('ksqldb', 'python'))
);

-- ============================================================================
-- Indexes
-- ============================================================================
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_timestamp ON transactions(transaction_timestamp DESC);
CREATE INDEX idx_transactions_category ON transactions(category);

CREATE INDEX idx_fraud_alerts_transaction_id ON fraud_alerts(transaction_id);
CREATE INDEX idx_fraud_alerts_account_id ON fraud_alerts(account_id);
CREATE INDEX idx_fraud_alerts_fraud_type ON fraud_alerts(fraud_type);
CREATE INDEX idx_fraud_alerts_detected_at ON fraud_alerts(detected_at DESC);
CREATE INDEX idx_fraud_alerts_risk_score ON fraud_alerts(risk_score DESC);

-- ============================================================================
-- Views
-- ============================================================================

-- Fraud statistics per hour/category
CREATE OR REPLACE VIEW fraud_statistics AS
SELECT
    DATE_TRUNC('hour', f.detected_at) AS hour,
    f.fraud_type,
    COUNT(*) AS alert_count,
    ROUND(AVG(f.amount), 2) AS avg_amount,
    ROUND(MAX(f.amount), 2) AS max_amount,
    COUNT(DISTINCT f.account_id) AS unique_accounts
FROM fraud_alerts f
GROUP BY DATE_TRUNC('hour', f.detected_at), f.fraud_type
ORDER BY hour DESC;

-- Account risk profile
CREATE OR REPLACE VIEW account_risk_profile AS
SELECT
    account_id,
    COUNT(*) AS total_alerts,
    MAX(risk_score) AS max_risk_score,
    ROUND(AVG(risk_score), 0) AS avg_risk_score,
    ROUND(SUM(amount), 2) AS total_flagged_amount,
    array_agg(DISTINCT fraud_type) AS fraud_types,
    MAX(detected_at) AS last_alert_at
FROM fraud_alerts
GROUP BY account_id
ORDER BY total_alerts DESC;

-- Grant permissions
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO streamguard;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO streamguard;

-- Comments
COMMENT ON TABLE transactions IS 'All raw financial transactions';
COMMENT ON TABLE fraud_alerts IS 'Fraud alerts from ksqlDB and Python engine';
COMMENT ON VIEW fraud_statistics IS 'Hourly fraud statistics by type';
COMMENT ON VIEW account_risk_profile IS 'Risk profile per account';
